// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  datasource: {
    // ALWAYS prefer DIRECT_URL (Session pooler :5432 or db.<ref>.supabase.co).
    // Transaction pooler (:6543) cannot run migrations reliably.
    url: process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"],
  },
});
