services:
  - type: web
    name: myassist-backend
    runtime: node
    region: singapore
    plan: free
    branch: main
    buildCommand: npm install --include=dev && npx prisma generate && npm run build && npx prisma migrate deploy
    startCommand: npm run start:prod
    healthCheckPath: /api/v1/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: API_PREFIX
        value: api/v1
      - key: STORAGE_DRIVER
        value: supabase
      - key: SUPABASE_STORAGE_BUCKET
        value: ticket-attachments
      - key: JWT_ACCESS_EXPIRES_IN
        value: 15m
      - key: JWT_REFRESH_EXPIRES_IN
        value: 7d
      - key: DATABASE_URL
        sync: false
      - key: DIRECT_URL
        sync: false
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: SUPABASE_PUBLISHABLE_KEY
        sync: false
      - key: SUPABASE_JWKS_URL
        sync: false
      - key: JWT_ACCESS_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        sync: false
      - key: APP_URL
        sync: false
